name: Deploy Django to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

   
      - name: Setup Python
        uses: samkirkland/ftp-deploy-action@v4.3.4
        with:
          python-version: '3.10'


      - name: Install Django
        run: |
          python -m pip install --upgrade pip
          pip install django

      
      - name: Collect Static
        run: |
          python manage.py collectstatic --noinput

      
      - name: Deploy Django App via FTP
        uses: samkirkland/ftp-deploy-action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./           
          server-dir: /home/${{ secrets.CPANEL_FTP_USER }}/django_app
          exclude: |
            **/_pycache_
            */.pyc
            venv/

      
      - name: Deploy Static Files
        uses: samkirkland/ftp-deploy-action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./static/  
          server-dir: /public_html/static
